Repository e3modelling/OPEN-PROM, pull requests merged in 2024-04, with the labels that each got.

#196 Python scripts
  scripts/README.md
  scripts/rv.py
Labels: enhancement

#199 Added: General Demand Function - QElecConsAll, QElecConsNonSub, QCons…
  equations.gms
Labels: documentation

#200 Python scripts
  scripts/README.md
  scripts/rs.py
  scripts/rv.py
Labels: enhancement

#201 Renamed equations and variables based on mapping
  MENA-PROM mapping - mena_prom_mapping.csv
  declarations.gms
  equations.gms
  input.gms
  preloop.gms
  solve.gms
Labels: enhancement

#210 Python scripts
  scripts/rr.py
  scripts/rs.py
  scripts/rv.py
Labels: enhancement

#211 rr.py bugfix
  scripts/rr.py
Labels: bug

#213 Resshare removal
  MENA-PROM mapping - mena_prom_mapping.csv
  OLD-NEW Mapping.csv
  declarations.gms
  equations.gms
  preloop.gms
Labels: enhancement

#214 README.md update
  scripts/README.md
Labels: documentation
